### ISSUE TITLE
distinction between automatic closing and user action

### ISSUE THREAD

**Issue by dominikcz** [zerodevx/svelte-toast#105]
Hi, I have a case where I have to make a distinction between situations when user clicks a toast in order to close it and another one, when toast autocloses. I've prepared a pull request #104 in which I add an event object as a second parameter for `onpop` callback. It is not required by my current needs to have an event object there, as a simple boolean flag would be enough. Looking forward, however, maybe it would be more appropriate to make this parameter an object, that would allow to be enhanced in future without breaking changes. It could be something like that:

```
onpop(id, details) => {
  if (details.autoClose) {
     console.log('closed by user')
  } else {
     console.log('closed automatically')
  } 
}
```

where details could be something like this:

```
details: {
  autoClose: false,
  originalEvent: <click>,
  .... whatever comes in future
}
```

Please let me know what you think about it.

**Comment by zerodevx** [comment]
Hey, thanks so much for the PR! 🙏 

I'll move this conversation to #104 - let's talk there.
