### ISSUE TITLE
[Feature Request] Allow multiple toast instances at different positions

### ISSUE THREAD

**Issue by asjur** [zerodevx/svelte-toast#18]
Like the title says, is there a way or will there be a way to specify per push the position of a toast?

I have a use-case where I would like to have a certain type of toast appear from the bottom of the screen and another where it would be ideal for it to be in the top right on the same page.

**Comment by zerodevx** [comment]
That's a good question. At the moment, multiple toast containers (and correspondingly, multiple toast stacks) is not supported - I'm assuming for your use-case, you'd like Type A toasts to appear in Position A, and at the same time, Type B toasts to appear in Position B, where both types may appear concurrently.

If you don't require both toasts to appear concurrently (or you don't need 2 toast stacks), then I think it's possible right now to dynamically change the toast container position when needed.

Adding support for multiple toast instances will be an interesting feature to add though. I'll think about what it entails and might add it in the next release. 😁

**Comment by asjur** [comment]
> That's a good question. At the moment, multiple toast containers (and correspondingly, multiple toast stacks) is not supported - I'm assuming for your use-case, you'd like Type A toasts to appear in Position A, and at the same time, Type B toasts to appear in Position B, where both types may appear concurrently.

This is the correct behaviour I am looking for.

> If you don't require both toasts to appear concurrently (or you don't need 2 toast stacks), then I think it's possible right now to dynamically change the toast container position when needed.

Sadly both toasts has the potential to show at the same time.

**Comment by zerodevx** [comment]
Edited the title to mark this as a feature request. We can use this issue to track progress or to hold discussions.

**Comment by zerodevx** [comment]
HI @asjur - this feature is added in the latest release. Essentially, you can now set a toast container target:

```html
<SvelteToast target="myNewContainer" options={{ ... }} />
```

and send toasts to that target:

```js
toast.push('Hello', { target: 'myNewContainer` })
```

More info here: https://github.com/zerodevx/svelte-toast#supporting-multiple-toast-containers

Will close this issue for now, but please re-open if you encounter any problems!
