### ISSUE TITLE
[Feature Request] A recommended way to clear all active toasts

### ISSUE THREAD

**Issue by DimitrisRK** [zerodevx/svelte-toast#20]
I see there is currently no method for complete toast cleanup.
Maybe a `clear` method would do the trick.
Another alternative would be to make `pop` method return count or the removed item itself.

Then, something like this would do the trick:
`while(toaster.pop());`

**Comment by zerodevx** [comment]
Hi, yes that's a good idea. Should be a trivial change to make `pop()` return perhaps the toast id. So

```js
while(toast.pop()) // this would work
```

Will add it in the next release!

**Comment by zerodevx** [comment]
Hi @DimitrisRK - there's now a recommended way to clear all active toasts:

```js
toast.pop(0)
```

More info here: https://github.com/zerodevx/svelte-toast#removing-multiple-toasts

Thanks so much for raising this issue - will close this for now but feel free to re-open if you encounter any problems!
