### ISSUE TITLE
[Help needed] Initialising toast on form submit, but render it after a redirect

### ISSUE THREAD

**Issue by heliumbrain** [zerodevx/svelte-toast#21]
Hi!

First of all, I know this is not directly related to svelte-toast and most likely comes down to my lack of knowledge about JS/Svelte/programming in general :) But I'll throw out the question here anyway, and if anyone can help I'll appreciate it.

On my login page I have a form that on submit calls my backend API to log the user in, and then redirects the user to the front page. Example:

```javascript
import { SvelteToast, toast } from '@zerodevx/svelte-toast';

...

onSubmit: async (values) => {
	await fetch(`${variables.apiPath}/auth/login`, {
		method: 'POST',
		credentials: 'include',
		body: new URLSearchParams(`username=${values.email}&password=${values.password}`)
	});

	await goto('/');
	toast.push('Success!', {
		theme: {
			'--toastBackground': '#48BB78',
			'--toastProgressBackground': '#2F855A'
		}
	});
}
```

This generates the toast, but it doesn't "stick" after the redirection to the homepage. Any ideas on how to solve this?

**Comment by zerodevx** [comment]
Hi! So for this question you'll definitely get more help from folks over at [Stackoverflow](https://stackoverflow.com/).

I'm not sure what framework (if any) you're using for your front-end project, but I'm assuming it's at least a [Single Page App](https://developer.mozilla.org/en-US/docs/Glossary/SPA) - else any redirection causes a new document load. If the toast doesn't "stick" in an SPA, I might look at where the `SvelteToast` container is being declared - in general it should be placed at the top-level app shell.

**Comment by heliumbrain** [comment]
Hi!

Thanks a lot for the quick response. I'm using SvelteKit (which I totally forgot to mention, sorry about that).

Your advise is exactly what I needed! I was declaring the container in the login-route, makes sense why that wouldn't work.


in `__layout.svelte`
```javascript
<script>
import { SvelteToast } from '@zerodevx/svelte-toast';
...
</script>

...

<SvelteToast />

...
```

in `login.svelte`
```javascript
<script>
import { toast } from '@zerodevx/svelte-toast';
...

onSubmit: async (values) => {
	await fetch(`${variables.apiPath}/auth/login`, {
		method: 'POST',
		credentials: 'include',
		body: new URLSearchParams(`username=${values.email}&password=${values.password}`)
	});

	await goto('/');
	toast.push('Success!', {
		theme: {
			'--toastBackground': '#48BB78',
			'--toastProgressBackground': '#2F855A'
		}
	});
}
</script>

```

Now it works. Appreciate you taking the time 👍

**Comment by zerodevx** [comment]
Glad you got that worked out! 👍

**Comment by carmas123** [comment]
This does not solve `redirect` from +page.server.ts in SvelteKit.

If you want to check if an user is logged in and can access to a specify part of app and you do that into `+page.server.ts` the toast will never showed.

For example if into your +page.server.ts check this and if it fail you do that:
```
...
throw redirect(302, '/login');
...
```

the problem remain.
