### ISSUE TITLE
Doesn't work on chrome?

### ISSUE THREAD

**Issue by ahmetkca** [zerodevx/svelte-toast#22]
toast notification push doesn't work on chrome but works on Firefox

**Comment by paul-schwendenman** [comment]
Do you have any more information on your system, chrome version, etc.? Have you tried other devices, etc. I am using this in a project and I haven't had issues with the notifications showing up in chrome.

**Comment by ahmetkca** [comment]
It's not working at all i can see that i pushed a notification i can print out the $toast variable and i am able to see there are notifications but they are not displayed at all

**Comment by paul-schwendenman** [comment]
Are you seeing the same issue with the demo?

https://zerodevx.github.io/svelte-toast/

Also could you provide more information about your system, the output of:

```
npx envinfo --system --npmPackages svelte,@zerodevx/svelte-toast,@sveltejs/kit,@sveltejs/adapter-node,@sveltejs/adapter-static,@sveltejs/adapter-begin,@sveltejs/adapter-netlify,@sveltejs/adapter-vercel vite --binaries --browsers
```

(I just copied the command from the sveltekit issue template)

**Comment by zerodevx** [comment]
Closing this for now - thanks for your help @paul-schwendenman !
