### ISSUE TITLE
Uncaught SyntaxError: indirect export not found: Lexer

### ISSUE THREAD

**Issue by Wadjetz** [zerodevx/svelte-toast#23]
Hello, i have some trouble to use this library with Vite.js v2.4.2. i have this error with Firefox
`Uncaught SyntaxError: indirect export not found: Lexer markdown-parser.js:68:9` and with chrome `Uncaught SyntaxError: The requested module '/node_modules/marked/src/Lexer.js?v=4ea01e18' does not provide an export named 'default'`

**Comment by zerodevx** [comment]
Seems like the logged error is on `markedjs` which isn't a dependency of `svelte-toast` - it's probably caused by another package you installed.
