### ISSUE TITLE
Update SvelteToastOptions type

### ISSUE THREAD

**Issue by LucianVoju** [zerodevx/svelte-toast#26]
First, thank you for this component.

I get this error : Argument of type '{ target: string; }' is not assignable to parameter of type 'SvelteToastOptions'.
when trying to toast.push('Hey!', { target: 'new' })

Also this  toast.push({ msg: 'Yo!', duration: 2000 }) results in an error. Argument of type '{ msg: string; duration: number; }' is not assignable to parameter of type 'string'.

SvelteToastOptions and push should be updated.

Thank you

**Comment by zerodevx** [comment]
Hi @LucianVoju - thanks for raising this. I've [corrected](https://github.com/zerodevx/svelte-toast/commit/d6a3fa158d104ae48d75ae102e000390ee1a2206) the typescript [declarations](https://github.com/zerodevx/svelte-toast/blob/master/src/index.d.ts) file that should fix your issues. 🤞 

Could you update svelte-toast to `v0.4.1` and try again? Thanks!

**Comment by zerodevx** [comment]
@LucianVoju - Shifting your comment https://github.com/zerodevx/svelte-toast/issues/25#issuecomment-889036326 here.

I can't replicate the errors you're seeing. Your editor might be picking up the old declaration file? Can you ensure that you're updated to the latest `v0.4.1` release and perhaps reset your editor workspace?

**Comment by LucianVoju** [comment]
Hello,

I have made your suggestions and now everything works fine. No more Ts errors.

Thank you

**Comment by zerodevx** [comment]
Glad it's sorted out. Closing this for now.
