### ISSUE TITLE
unexpected token while importing

### ISSUE THREAD

**Issue by basaran** [zerodevx/svelte-toast#27]
Hello,

Thank you for the component. I have a rather odd error during import using sveltekit:

```
import { toast } from "$lib/helpers.js";
```

```
SyntaxError: Unexpected token (15:1380)...
```

Import statement works fine if I was to import from within the `.svelte` components inside `routes`. However, if I import anywere else, whether it's a js file, or a svelte component then it breaks the svelte compiler, even if you don't export.

helpers.js
```
import { toast } from "@zerodevx/svelte-toast";
export const something  = "anything";
````

something.svelte
```
import { something } from "../lib/helpers.js"
```

Refresh and it throws, if you could provide any assistance that would be great.

```
"svelte": "^3.34.0",
"@sveltejs/kit": "^1.0.0-next.138",
"@zerodevx/svelte-toast": "^0.4.1"
```

**Comment by zerodevx** [comment]
Hi there - I just want to check if this issue has anything to do with the latest `svelte-toast` release. Could you roll back to `v0.3.0` and let me know how it goes? You can run this on your command-line:

```
$ npm i @zerodevx/svelte-toast@0.3.0
```

Thanks!

**Comment by basaran** [comment]
Hello, yep that worked just fine :)

**Comment by basaran** [comment]
Okay, so it did work when I tried because I had the emit button already there, and I didn't need to refresh the UI. The moment I refresh svelte gave the same error.

So, the situation doesn't seem to be related to the version of svelte-toast. The moment you refresh, svelte breaks. I figured I should also try to compile, this time I was able to get a more meaningful error.

```
Unexpected token (Note that you need plugins to import files that are not JavaScript)
file: /home/michael/websites/qt-client/node_modules/@zerodevx/svelte-toast/src/ToastItem.svelte:10:1258
 8: const css = {
 9:   code: "._toastItem.svelte-1y8g5o1{-webkit-tap-highlight-color:transparent;align-items:center;background:var(--toastBackground,rgba(66,66,66,.9));border-radius:var(--toastBorderRadius,.125rem);box-shadow:var(--toastBoxShadow,0 4px 6px -1px rgba(0,0,0,.1),0 2px 4px -1px rgba(0,0,0,.06));color:var(--toastColor,#fff);display:flex;flex-direction:row;height:var(--toastHeight,auto);margin:var(--toastMargin,0 0 .5rem 0);min-height:var(--toastMinHeight,3.5rem);position:relative;width:var(--toastWidth,16rem);will-change:transform,opacity}._toastMsg.svelte-1y8g5o1{flex:1 1 0%;padding:var(--toastMsgPadding,.75rem .5rem)}._toastMsg.svelte-1y8g5o1 a{pointer-events:auto}._toastBt
```

**Comment by basaran** [comment]
I was able to find the culprit:

```
._toastMsg :global(a) {
  pointer-events: auto;
}
```

**Comment by zerodevx** [comment]
Thanks for the deep-dive. It's strange that the `:global()` modifier is causing an error since it's [standard Svelte syntax](https://svelte.dev/docs#style). Give me some time to get back to you on this one - I'll fire up an instance of SvelteKit and try to reproduce the issue.

**Comment by basaran** [comment]
well, I went ahead and tried on a clean skeleton project and there didn't appear to be any problems with anything. This could have something to do with postcss and my other scss files

**Comment by zerodevx** [comment]
@basaran hey, so I finally had the chance to use this in a clean SvelteKit project and I'm not encountering any issues. Did you manage to resolve this?

**Comment by basaran** [comment]
hi, yeah it's still there. It has something to do with svelte-preprocess. I will make you a base repo later today.

**Comment by basaran** [comment]
Hi, I think I found the culprit, it's rather odd though. I have this in my `svelte.config.js`

```
vite: {
  define: {
     global: {
       whatever: "nahahhhhhh", //this is the problem
      },
},
```

I have no idea why but if I add a global to vite configuration, svelte compiler throws that error with the global styles. May be it's overwriting something. Could you test this too please? Once you add and relaunch dev, you should have something like:

![image](https://user-images.githubusercontent.com/30809170/135161529-3683c68e-1773-41a5-8aa1-feff8c769597.png)

in your console.

**Comment by zerodevx** [comment]
According to [Vite's manual](https://vitejs.dev/config/#mode): 

> Because it's implemented as straightforward text replacements without any syntax analysis, we recommend using define for CONSTANTS only.

> For example, process.env.FOO and __APP_VERSION__ are good fits. But process or global should not be put into this option. Variables can be shimmed or polyfilled instead.

you shouldn't define `global` (or `process`) here.

This is almost certainly a SvelteKit/Vite issue so you might get more help over there. 🤷

**Comment by basaran** [comment]
yep, well I suppose we can close this now, there is enough information here in case somebody comes to it. Thank you for looking into it.
