### ISSUE TITLE
Can load lazily?

### ISSUE THREAD

**Issue by bitdom8** [zerodevx/svelte-toast#41]
Lazy load would be great

**Comment by zerodevx** [comment]
What do you mean by lazily?

**Comment by bitdom8** [comment]
Yes exactly

**Comment by zerodevx** [comment]
What I mean is - how does lazy loading work? Do you mean loading dynamically (dynamic imports)? Are you using this as a Svelte component or in vanilla js?

**Comment by bitdom8** [comment]
I used both:

Tried this, not working:
```

import { toast } from '@zerodevx/svelte-toast'
// import type { toast } from '$lib/types';
// import Push from 'push.js';
let Push
// let toast : {}
setTimeout(async function () {
	// toast = (await import('@zerodevx/svelte-toast'));
	Push = (await import('push.js')).default;

}, 11000);

```

**Comment by zerodevx** [comment]
`toast` and `SvelteToast` are named exports so the syntax should look like:

```js
...
const { toast } = await import('@zerodevx/svelte-toast')
```

**Comment by bitdom8** [comment]
Thx, how about defining it as top level element. Got an error: 

`Top-level 'await' expressions are only allowed when the 'module' option is set to 'es2022', 'esnext', 'system', or 'nodenext', and the 'target' option is set to 'es2017' or higher.`

**Comment by zerodevx** [comment]
That looks like a linter error. Just do as the message suggests - set your `.eslintrc` file with:

```json
{
  ...
  "module": "esnext",
  "target": "es2017"
}
```

**Comment by bitdom8** [comment]
Thanks @zerodevx , do you have stacksoverflow account? wanna follow you

**Comment by zerodevx** [comment]
I do - it's `@zerodevx` but I've not really been active there =/

In the meantime - will mark this issue as closed, feel free to reopen if there are issues.
