### ISSUE TITLE
Document that `initial: 0` waits for user to dismiss toast

### ISSUE THREAD

**Issue by tv42** [zerodevx/svelte-toast#43]
I had to reverse engineer this from the component example on https://zerodevx.github.io/svelte-toast/:

https://github.com/zerodevx/svelte-toast/blob/9d234a7cde7a8fbecef07f63e13991724907b7e9/docs/App.svelte#L247-L262

**Comment by zerodevx** [comment]
Added additional examples (and extra comments) in the [demo](https://zerodevx.github.io/svelte-toast/) that would hopefully help clarify.
