### ISSUE TITLE
Style not working

### ISSUE THREAD

**Issue by stojanni** [zerodevx/svelte-toast#47]
I installed and setup the package as instructed but when i call it i only get a couple letters on the corner with a very small blue line.

**Comment by zerodevx** [comment]
Sounds like something is overriding the toast styles. Need more info like what other frameworks/components you're using, examples/reproductions etc.

**Comment by zerodevx** [comment]
If there are like interfering stylesheets in effect, the best way is to inspect the path through browser dev-tools. Going to mark this as closed for now, feel free to re-open if there are issues regarding the component itself.
