### ISSUE TITLE
Anyway to make the toast clickable?

### ISSUE THREAD

**Issue by 203Null** [zerodevx/svelte-toast#49]
I want to create a toast with a click handler, not sure if that is doable.

**Comment by zerodevx** [comment]
You can [send a component as a message](https://github.com/zerodevx/svelte-toast#send-svelte-component-as-a-message). There's an example in the [demo](https://zerodevx.github.io/svelte-toast/). Does that help?

**Comment by 203Null** [comment]
> You can [send a component as a message](https://github.com/zerodevx/svelte-toast#send-svelte-component-as-a-message). There's an example in the [demo](https://zerodevx.github.io/svelte-toast/). Does that help?

Yes! I have no idea how did I miss that one after playing with it for a pretty long time haha. Thank you

**Comment by 203Null** [comment]
What I planning to do is something that is basically the same as a regular toast (with an expiration time) but just a button on the right, like
`| Something happened [Action]|`

I don't know if this is something doable.

**Comment by zerodevx** [comment]
Check out this repl: https://svelte.dev/repl/0ad7e21471994688b6013c4d6deec5a4?version=3.49.0

**Comment by 203Null** [comment]
> Check out this repl: https://svelte.dev/repl/0ad7e21471994688b6013c4d6deec5a4?version=3.49.0

Thank you!

**Comment by zerodevx** [comment]
Glad to help!

**Comment by 203Null** [comment]
Is it possible to make the entire toast clickable?
