### ISSUE TITLE
Update Custom Component Props

### ISSUE THREAD

**Issue by jrmoynihan** [zerodevx/svelte-toast#51]
I seem to be unable to update the props of a custom toast component after it is initialized.  I'm aiming to do something like this:

```js
import CustomToast from './CustomToast.svelte'
import type {ComponentProps} from 'svelte'
import type {SvelteToastOptions} from '@zerodevx/svelte-toast'

async function myCustomToast({toast_options: SvelteToastOptions, component_props: ComponentProps<CustomToast>, id?: number}) : number {

    	const toastProps: SvelteToastOptions = {
		...toast_options,
                component: {
			src: CustomToast, // my custom component
			props: component_props,		}
	};

	if (id !== undefined && id !== null) {
		toast.set({ id, ...toastProps });
	} else {
		id = toast.push(toastProps);
	}
	return id;
}
```

Now if I call the following, I only get the first toast to appear:
```js
async function updateCustomComponentStatus(){
   const id = await myCustomToast({toast_options: { initial: 0 }, component_props: { msg: 'Starting a long workflow...'}})
   for(let i = 0; i < 10_000; i++) {
       await someLongFunction()
       // This should call toast.set with the params, because we passed in an id
       await myCustomToast({component_props: {msg: `Finished item ${i} / 10,000`}, id})
    }
}
```
But if you do this, it works just fine:
```js
function updateDefaultToastStatus() {
    const id = toast.push({msg: 'Starting a long workflow', initial: 0})
       for(let i = 0; i < 10_000; i++){
       someLongFunction()
       toast.set({msg: `Finished item ${i} / 10,000`, id})
    }
}
```

In other words, the `set` function doesn't appear to be able to update the custom msg component, like it does with the msg when you use the package's default toast.

Is there a way to do this?  Perhaps you just need to reference the component instance in a writable store somewhere?

**Comment by zerodevx** [comment]
Hi, thanks for raising this. I reproduced your code here (https://svelte.dev/repl/5ab72393c38b4cbd81682499624bf669?version=3.50.1) and can confirm that there's a bug. I *think* I know what's wrong and I'll submit a bugfix soon.

**Comment by zerodevx** [comment]
This should be fixed. Using the same reproduction (https://svelte.dev/repl/97a5e88cd54b43e7b046580625b5da74?version=3.50.1), looks ok now. I've cut a temp [release](https://github.com/zerodevx/svelte-toast/releases/tag/v0.7.3-rc.1) that you can install with the `@next` tag if you're in a rush - meanwhile, I'll add a regression test (and work on another issue) before I'll release the latest.

**Comment by jrmoynihan** [comment]
@zerodevx Thanks for the quick response and fix!  I can confirm it's working.
