### ISSUE TITLE
Close 'X' is not showing correctly

### ISSUE THREAD

**Issue by nickakin** [zerodevx/svelte-toast#54]
The close 'X' icon is not rendering correctly, instead it is getting translated to: âœ•

It would be nice to be able to set an icon instead.

<img width="260" alt="image" src="https://user-images.githubusercontent.com/82688431/194908113-4093c5ba-9dbb-4b38-bdb3-9d7df70f04a0.png">

**Comment by zerodevx** [comment]
Hi, that's probably due to differences in the installed system font stack. 😞  I just added a way for you use a SVG icon instead, like so:

```html
<script>
import { toast, SvelteToast } from '@zerodevx/svelte-toast'

const options = {
  theme: {
    // Note that you may have to set the width/height inside the SVG itself, perhaps as attributes
    '--toastBtnContent': `url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' ...")`
  }
}
</script>

<button on:click={() => toast.push('Ping!')}>PONG</button>

<SvelteToast {options} />
```

Alternatively, you can just replace the default character to something else, like a dash instead:

```js
theme: {
  '--toastBtnContent': `"-"`
}
```
