### ISSUE TITLE
Cannot read properties of undefined (reading 'SvelteToast')

### ISSUE THREAD

**Issue by Ddupasquier** [zerodevx/svelte-toast#65]
SvelteToast is sometimes undefined? I'm honestly not even sure where to start with this. I've never had a component show as undefined before haha. Any thoughts?

The SvelteToast component lives directly in my root +layout.svelte, so there's no reason for it to ever unmount.

```js
<script lang="ts">
	import { onMount } from 'svelte';
	import { supabase } from '$lib/supabase';
	import { signout, getProfile } from '$lib/services/auth';
	import './styles.scss';

	import type { AuthSession } from '@supabase/supabase-js';
	
	import Header from './Header.svelte';
	import Footer from './Footer.svelte';
	import { SvelteToast } from '@zerodevx/svelte-toast';

	const options = {
		position: 'top-right',
		duration: 3000
	};

	export let data: { session: AuthSession | null };

	onMount(() => {
		getProfile(data.session?.user.id);
	});
</script>

<div class="app">
	<SvelteToast {options} />
	<Header session={data.session} />
	{#if data.session}
		<button
			type="button"
			on:click={() => {
				supabase.auth.signOut();
				signout();
			}}
			class="button logout"
		>
			Sign Out
		</button>
	{/if}

	<main>
		<slot session={data.session} />
	</main>

	<Footer />
</div>
```

From within my services folder I'm just doing your simple toast.push().
```js
export const downloadAvatar = async (path: string) => {
	try {
		const { data, error } = await supabase.storage.from('avatars').download(path);

		if (error) {
			toast.push(`Something went wrong! ${error.message}`, { duration: 5000, pausable: true })
			throw error;
		}

		const url = URL.createObjectURL(data);
		return url;
	} catch (error) {
		if (error instanceof Error) {
			toast.push(`Something went wrong! ${error.message}`, { duration: 5000, pausable: true })
		}
	}
};
```

**Comment by zerodevx** [comment]
From your code:

```html
<script>
  ...
  const options = {
    position: 'top-right',
    duration: 3000
  }
</script>

<SvelteToast {options} />
```

`position` is not a valid option. Use CSS vars to position the container.

**Comment by Ddupasquier** [comment]
> From your code:
> 
> ```
> <script>
>   ...
>   const options = {
>     position: 'top-right',
>     duration: 3000
>   }
> </script>
> 
> <SvelteToast {options} />
> ```
> 
> `position` is not a valid option. Use CSS vars to position the container.

OH! I actually don't even understand why I thought that might be valid xD
Does this component default to the top right?
Like basically top 3% x right 0%?

**Comment by zerodevx** [comment]
> Does this component default to the top right?

Yup.

> Like basically top 3% x right 0%?

Specifically, it defaults to:

```css
  top: var(--toastContainerTop, 1.5rem);
  right: var(--toastContainerRight, 2rem);
  bottom: var(--toastContainerBottom, auto);
  left: var(--toastContainerLeft, auto);
```

**Comment by Ddupasquier** [comment]
> > Does this component default to the top right?
> 
> Yup.
> 
> > Like basically top 3% x right 0%?
> 
> Specifically, it defaults to:
> 
> ```css
>   top: var(--toastContainerTop, 1.5rem);
>   right: var(--toastContainerRight, 2rem);
>   bottom: var(--toastContainerBottom, auto);
>   left: var(--toastContainerLeft, auto);
> ```

Omfg, I feel dumb as heck. Fully understandable if you remove this from 'issues' :p
Not an issue. Just my stupidity.

**Comment by zerodevx** [comment]
No worries - closing this for now.
