### ISSUE TITLE
what was your special reason to avoid using the semicolon in your JS code?

### ISSUE THREAD

**Issue by vikbert** [zerodevx/svelte-toast#7]
A reference shows the arguments that you should not miss the semicolon in js code. https://stackoverflow.com/questions/444080/do-you-recommend-using-semicolons-after-every-statement-in-javascript

**Comment by zerodevx** [comment]
Write less code to fit the `Svelte` narrative; and at the same time save my semi-colon key? 🤣 

Seriously, not going down the rabbit-hole on this one. 🤣 🤣 🤣 

I'm fine both ways actually, but I just use (the misleadingly named) [Standardjs](https://standardjs.com/) and try not to think too much. The linter does a pretty good job catching pitfalls.

You may find these discussions interesting though:
* https://github.com/standard/standard/issues/5
* https://github.com/standard/standard/issues/78
* https://github.com/maxogden/messages/issues/18

**Comment by vikbert** [comment]
it was boring that if vs-code-prettier add always the semi-colon after saving, as it does for most of my other projects. But the eslint in this project detect the newly added semi as error. Any good idea to avoid the conflict?

**Comment by zerodevx** [comment]
IMO code styles doesn't matter if you're consuming/adding a package; it only matters when contributing to a project. In this case, IMO usage of the `vs-code-prettier` extension should be opt-in on a per-project basis (with the setting `Prettier: Require config` enabled - so projects that enforce this code style adds a `.prettierrc` file. 

In general, code styling should be a trivial issue though.

I'll suggest disabling `vs-code-prettier` (or enabling the above setting) for this project; or you can use the `Standardjs` extension; or you can also run `eslint --fix` before committing.
