### ISSUE TITLE
Svelte 4 support

### ISSUE THREAD

**Issue by space-nuko** [zerodevx/svelte-toast#83]
Hello, Svelte 4 was recently released. Could this library be upgraded to support it? Thank you

https://svelte.dev/blog/svelte-4#migrating

**Comment by zerodevx** [comment]
Done! 

https://github.com/zerodevx/svelte-toast/releases/tag/v0.9.4

**Comment by aam-git** [comment]
Hi, Can you do the RC version too?

Thanks

**Comment by zerodevx** [comment]
@aam-git Hey, IFAIK the RC version shouldn't be required now? The latest `v0.9.4` includes everything, and more. Definitely recommend that you switch to `@latest`.

```
$ npm i --save @zerodevx/svelte-toast@latest
```

**Comment by aam-git** [comment]
> @aam-git Hey, IFAIK the RC version shouldn't be required now? The latest `v0.9.4` includes everything, and more. Definitely recommend that you switch to `@latest`.
> 
> ```
> $ npm i --save @zerodevx/svelte-toast@latest
> ```

Last time I tried 0.9x it didn't work with my system, I'll try it again later.  Thanks.
