### ISSUE TITLE
line break

### ISSUE THREAD

**Issue by dilmaev** [zerodevx/svelte-toast#90]
Hello everyone, please tell me how to make a line break?

toasts.add({ 
        description: `Speed: 123Mbit\n\nPing: 123<br>test\rtest`,
        duration: 0,
        placement: 'bottom-right',
        type: 'success',
        // showProgress: true,
        theme: 'dark',
      })

not working

**Comment by dilmaev** [comment]
gg, sorry

**Comment by zerodevx** [comment]
Doesn't seem like you're using this project. Closing for now.
